[package]
authors = ["Kornel <pornel@pornel.net>"]
categories = ["multimedia::images", "command-line-utilities"]
description = "Measures structural similarity between images using a multi-scale variant of the SSIM algorithm."
documentation = "https://docs.rs/dssim"
homepage = "https://kornel.ski/dssim"
include = ["README.md", "Cargo.toml", "src/*.rs", "LICENSE"]
keywords = ["ssim", "image", "comparison"]
license = "AGPL-3.0"
name = "dssim"
readme = "README.md"
repository = "https://github.com/kornelski/dssim.git"
version = "2.11.1"
edition = "2018"

[[bin]]
doctest = false
name = "dssim"
path = "src/main.rs"

[dependencies]
getopts = "0.2.21"
imgref = "^1.4"
itertools = "0.9.0"
lodepng = "3.0.0"
rayon = "1.3.1"
rgb = "0.8.20"
load_image = { version = "2.12.1", features = ["static"] }

[lib]
doctest = false
name = "dssim"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
